name: docs_pages_workflow

on:
  workflow_dispatch

#on:
#  push:
#    branches: [main]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autoapi

      - name: Generate .rst files
        run: |
          sphinx-apidoc -o docs/source/ your_module/  # Replace 'your_module' with your code directory

      - name: Build Sphinx Docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Prepare and Deploy to GitHub Pages
        run: |
          cd docs/build/html
          touch .nojekyll
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Deploy updated docs"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
