name: docs_pages_workflow

#on:
#  workflow_dispatch
on:
 push:
   branches:
     - main

jobs:
  build_docs_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autoapi

      - name: Generate .rst files
        run: |
          
          find docs/source/ -type f -name "*.rst" -delete
          
          sphinx-apidoc -f -o docs/source/ automation_libs/automation_libs_1/example
          sphinx-apidoc -f -o docs/source/ automation_libs/automation_libs_1/test
          sphinx-apidoc -f -o docs/source/ automation_libs/automation_libs_1/test2
      

      - name: Commit updated .rst files
        run: |
          git add docs/source/
          git commit -m "Update .rst files" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      - name: Build Sphinx Docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: docs/build/html
