name: docs_pages_workflow

on:
  workflow_dispatch  # Allows manual triggering of the workflow

permissions:
  contents: write  # 🔥 Gives GitHub Actions write access

jobs:
  build_docs_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autoapi

      - name: Generate .rst files
        run: |
          sphinx-apidoc -o docs/source/ your_module/  # Replace with your actual module

      - name: Build Sphinx Docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Deploy to GitHub Pages
        run: |
          cd docs/build/html
          touch .nojekyll
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Deploy updated docs"
          
          # Set remote repository
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          
          git push --force origin HEAD:gh-pages
